import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from pikepdf import Pdf
from pdform import fill_form

pdf = Pdf.open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'pdfs', 'VBA-21-22-ARE.pdf'))
fill_form(pdf, {
    # 3. V. A. File Number (if applicable). Enter nine digit file number.",
    "F[0].Page_1[0].VAFileNumber[0]": "123456789",
    # See Important information and Note above. SECTION 1: VETERAN'S INFORMATION. NOTE: You can either complete the form online or by hand. If completed by hand, print the information requested in ink, neatly, and legibly to expedite processing the form. 1. VETERAN'S NAME (First, Middle Initial, Last). Enter First Name. 12 characters max.",
    "F[0].Page_1[0].VeteransFirstName[0]": "Harry",
    # 1. Veteran's Name. Enter Last Name. 18 characters max.",
    "F[0].Page_1[0].VeteransLastName[0]": "Harrison",
    # 1. Veteran's Name. Enter Middle Initial. 1 character max.",
    "F[0].Page_1[0].VeteransMiddleInitial1[0]": "H",
    # 2. Veteran's Social Security Number. Enter first three numbers.",
    "F[0].Page_1[0].SocialSecurityNumber_FirstThreeNumbers[0]": "123",
    # 2. Veteran's Social Security Number. Enter middle two numbers.",
    "F[0].Page_1[0].SocialSecurityNumber_SecondTwoNumbers[0]": "45",
    # 2. Veteran's Social Security Number. Enter last four numbers.",
    "F[0].Page_1[0].SocialSecurityNumber_LastFourNumbers[0]": "6789",
    # 4. Veteran's Date of Birth. Enter 2 digit Month.  ",
    "F[0].Page_1[0].DOBmonth[0]": "09",
    # 4. Veteran's Date of Birth. Enter 2 digit day.",
    "F[0].Page_1[0].DOBday[0]": "19",
    # 4. Veteran's Date of Birth. Enter 4 digit year.",
    "F[0].Page_1[0].DOByear[0]": "1990",
    # 5. Veteran's Service Number (If applicable). Enter 9 digits.",
    "F[0].Page_1[0].VeteransServiceNumber_If_Applicable[0]": "123456789",
    # 12. CLAIMANT'S TELEPHONE NUMBER (Include Area Code).  ",
    "F[0].Page_1[0].TelephoneNumber_IncludeAreaCode[0]": "(987)654-3210",
    # 6. INSURANCE NUMBER(S) (If applicable) (Include letter prefix).",
    "F[0].Page_1[0].InsuranceNumber_s[0]": "123456789",
    # SECTION 2: CLAIMANT'S INFORMATION. (If other than veteran). 10. Claimant's Name (First, Middle Initial, Last). Enter First Name. 12 characters max.",
    "F[0].Page_1[0].Claimants_FirstName[0]": "Harriet",
    # 10. Claimant's Name. Enter Last Name. 18 characters max.",
    "F[0].Page_1[0].Claimants_LastName[0]": "Harrison",
    # 10. Claimant's Name. Enter Middle Initial. 1 character max.",
    "F[0].Page_1[0].Claimants_MiddleInitial1[0]": "H",
    # 11. CLAIMANT'S MAILING ADDRESS (Number and street or rural route, P. O. Box, City, State, ZIP Code and Country). Enter Number and Street. 30 characters max.",
    "F[0].Page_1[0].Claimants_MailingAddress_NumberAndStreet[0]": "123 Main St",
    # 11. CLAIMANT'S MAILING ADDRESS. Enter Apartment or Unit Number. 5 characters max.",
    "F[0].Page_1[0].Claimants_MailingAddress_ApartmentOrUnitNumber[0]": "404",
    # 11. CLAIMANT'S MAILING ADDRESS. Enter City. 18 characters max.",
    "F[0].Page_1[0].Claimants_MailingAddress_City[0]": "Anywhere",
    # 11. CLAIMANT'S MAILING ADDRESS. Enter State or Province. 2 characters max.",
    "F[0].Page_1[0].Claimants_MailingAddress_StateOrProvince[0]": "NE",
    # 11. CLAIMANT'S MAILING ADDRESS. Enter Country. 2 characters max.",
    "F[0].Page_1[0].Claimants_MailingAddress_Country[0]": "USA",
    # 11. CLAIMANT'S MAILING ADDRESS. Enter ZIP or Postal Code. Enter first 5 digits.",
    "F[0].Page_1[0].Claimants_MailingAddress_ZIPOrPostalCode_FirstFiveNumbers[0]": "12345",
    # 11. CLAIMANT'S MAILING ADDRESS. Enter ZIP or Postal Code. Enter last 4 digits.",
    "F[0].Page_1[0].Claimants_MailingAddress_ZIPOrPostalCode_LastFourNumbers[0]": "6789",
    # 13. CLAIMANT'S EMAIL ADDRESS (Optional).  ",
    "F[0].Page_1[0].Claimants_EmailAddress_Optional[0]": "hh@example.com",
    # 14. RELATIONSHIP TO VETERAN.",
    "F[0].Page_1[0].Relationship_To_Veteran[0]": "Wife",
    # 8. VETERAN'S TELEPHONE NUMBER (Include Area Code).  ",
    "F[0].Page_1[0].TelephoneNumber_IncludeAreaCode[1]": "(321)654-7890",
    # 9. VETERAN'S EMAIL ADDRESS (Optional).  ",
    "F[0].Page_1[0].EmailAddress_Optional[0]": "harry@example.com",
    # SECTION 3: SERVICE ORGANIZATION INFORMATION. 15. NAME OF SERVICE ORGANIZATION RECOGNIZED BY THE DEPARTMENT OF VETERANS AFFAIRS  (See list on page 3 before selecting organization).",
    "F[0].Page_1[0].Name_Of_Service_Organization[0]": "The American Legion",
    # 16. A. NAME OF OFFICIAL REPRESENTATIVE ACTING ON BEHALF OF THE ORGANIZATION NAMED IN ITEM 15 (This is an appointment of the entire organization and does not indicate the designation of only this specific individual to act on behalf of the organization).",
    "F[0].Page_1[0].Name_Of_Official_Representative[0]": "Mary Rosemary",
    # 16B. JOB TITLE OF PERSON NAMED IN ITEM 16. A.",
    "F[0].Page_1[0].Job_Title_Of_Person_Named_In_Item15A[0]": "CVSO",
    # 17. EMAIL ADDRESS OF ORGANIZATION NAMED IN ITEM 15.",
    "F[0].Page_1[0].Email_Address[0]": "mary@example.org",
    # 7. VETERAN'S MAILING ADDRESS (Number and street or rural route, P. O. Box, City, State, ZIP Code and Country). Enter Number and Street. 30 characters max.",
    "F[0].Page_1[0].Claimants_MailingAddress_NumberAndStreet[1]": "123 Main St",
    # 7. VETERAN'S MAILING ADDRESS. Enter Apartment or Unit Number. 5 characters max.",
    "F[0].Page_1[0].Claimants_MailingAddress_ApartmentOrUnitNumber[1]": "404",
    # 7. VETERAN'S MAILING ADDRESS. Enter City. 18 characters max.",
    "F[0].Page_1[0].Claimants_MailingAddress_City[1]": "Anywhere",
    # 7. VETERAN'S MAILING ADDRESS. Enter State or Province. 2 characters max.",
    "F[0].Page_1[0].Claimants_MailingAddress_StateOrProvince[1]": "NE",
    # 7. VETERAN'S MAILING ADDRESS. Enter Country. 2 characters max.",
    "F[0].Page_1[0].Claimants_MailingAddress_Country[1]": "USA",
    # 7. VETERAN'S MAILING ADDRESS. Enter ZIP or Postal Code. Enter first 5 digits.",
    "F[0].Page_1[0].Claimants_MailingAddress_ZIPOrPostalCode_FirstFiveNumbers[1]": "12345",
    # 7. VETERAN'S MAILING ADDRESS. Enter ZIP or Postal Code. Enter last 4 digits.",
    "F[0].Page_1[0].Claimants_MailingAddress_ZIPOrPostalCode_LastFourNumbers[1]": "6789",
    # 20. LIMITATION OF CONSENT - I authorize disclosure of records related to treatment for all conditions listed in Item 19, except: DRUG ABUSE.",
    "F[0].Page_2[0].Drug_Abuse[0]": False,
    # 21. AUTHORIZATION TO CHANGE CLAIMANT'S ADDRESS - By checking the box below, I authorize the organization named in Item 15 to act on my behalf to change my address in V. A. records. I authorize any official representative of the organization named in Item 15 to act on my behalf to change my address in my V. A. records. This authorization does not extend to any other organization without my further written consent. This authorization will remain in effect until the earlier of the following events: (1) I file a written revocation with V. A.; or (2) I appoint another representative, or (3) I have been determined unable to manage my financial affairs and the individual or organization named in Item 16. A. is not my appointed fiduciary.",
    "F[0].Page_2[0].I_Authorize[0]": True,
    # 20. ALCOHOLISM OR ALCOHOL ABUSE.",
    "F[0].Page_2[0].Alcoholism_Or_Alcohol_Abuse[0]": False,
    # 20. INFECTION WITH THE HUMAN IMMUNODEFICIENCY VIRUS (H I V).",
    "F[0].Page_2[0].Infection_With_The_Human_Immunodeficiency_Virus_HIV[0]": False,
    # 20. SICKLE CELL ANEMIA. ",
    "F[0].Page_2[0].sicklecellanemia[0]": False,
    # SECTION 4: AUTHORIZATION INFORMATION. 19. AUTHORIZATION FOR REPRESENTATIVE'S ACCESS TO RECORDS PROTECTED BY SECTION 73 32, TITLE 38, U. S. C. - By checking the box below I authorize V. A. to disclose to the service organization named on this appointment form any records  that may be in my file relating to treatment for drug abuse, alcoholism or alcohol abuse, infection with the human immunodeficiency virus (H I V), or sickle cell anemia. I authorize the V. A. facility having custody of my V. A. claimant records to disclose to the service organization named in Item 15 all treatment records relating to drug abuse, alcoholism or alcohol abuse, infection with the human immunodeficiency virus (H I V), or sickle cell anemia. Redisclosure of these records by my service organization representative, other than to V. A. or the Court of Appeals for Veterans Claims, is not authorized without my further written consent. This authorization will remain in effect until the earlier of the following events: (1) I revoke this authorization by filing a written revocation with V. A.; or (2) I revoke the appointment of the service organization named in Item 15, either by explicit revocation or the appointment of another representative.",
    "F[0].Page_2[0].I_Authorize[1]": True,
    # SECTION 5: SIGNATURES. NOTE: THIS POWER OF ATTORNEY DOES NOT REQUIRE EXECUTION BEFORE A NOTARY PUBLIC. 22. A. SIGNATURE OF VETERAN OR CLAIMANT (Do Not Print). This is a digital signature field.",
    "F[0].Page_2[0].SignatureField1[0]": os.path.join(os.path.dirname(os.path.abspath(__file__)), 'resources', 'sigtest.jpg'),
    # 23. A. SIGNATURE OF VETERANS SERVICE ORGANIZATION REPRESENTATIVE NAMED IN ITEM 16. A. (Do Not Print). This is a digital signature field.",
    "F[0].Page_2[0].SignatureField1[1]": os.path.join(os.path.dirname(os.path.abspath(__file__)), 'resources', 'duck.jpg'),
    # 22B. DATE SIGNED. Enter 2 digit month, 2 digit day and 4 digit year.",
    "F[0].Page_2[0].DateSigned[0]": "12/24/2024",
    # 23B. DATE SIGNED. Enter 2 digit month, 2 digit day and 4 digit year.",
    "F[0].Page_2[0].DateSigned[1]": "12/24/2024",
    # 2. Veteran's Social Security Number. Enter first three numbers.",
    "F[0].Page_2[0].SocialSecurityNumber_FirstThreeNumbers[0]": "123",
    # 2. Veteran's Social Security Number. Enter middle two numbers.",
    "F[0].Page_2[0].SocialSecurityNumber_SecondTwoNumbers[0]": "45",
    # 2. Veteran's Social Security Number. Enter last four numbers.",
    "F[0].Page_2[0].SocialSecurityNumber_LastFourNumbers[0]": "6789",
})
pdf.save(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'output', 'fill_form_VBA-21-22-ARE.pdf'))
